version: '3.7'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

    volumes:
      - ./mysql:/var/lib/mysql
      #- ./data:/var/lib/mysql
      - ./src/test/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      #- ./resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      #- C:\Users\Lexxs\IdeaProjects\HomeWork_07_01_Sql\src\test\resources\schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
   # command:
     # - mysqld --init-file="/src/test/resources/schema.sql"
     # - docker exec -i app sh -c 'exec mysql -uroot -p"pass"' < /var/lib/mysql/schema.sql